apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: test-nginx-2
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: test-nginx-2-container
        image: shrestharajat.azurecr.io/nginx/testnginx:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: test-nginx-2
